[package]
name = "treereduce-c"
description = "Fast, syntax-aware program reducer (delta debugger) for C"
version = "0.0.0"
keywords = ["delta-debugging", "program-reducer", "c"]
edition = "2021"
authors = ["Langston Barrett <langston.barrett@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/langston-barrett/treereduce"
repository = "https://github.com/langston-barrett/treereduce"

[dependencies]
anyhow = "1.0"
treereduce = { version = "0.0.0", path = "../treereduce", features = ["cli"] }
tree-sitter-c = "0.20"